// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHMWEZlKtJp7FHcyuxv7fA1rP9vWAIZO4',
    appId: '1:696407976562:web:1dc84e0512a65faf18f0eb',
    messagingSenderId: '696407976562',
    projectId: 'test-work-app-4bb89',
    authDomain: 'test-work-app-4bb89.firebaseapp.com',
    storageBucket: 'test-work-app-4bb89.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ3A6EG8OMW--mCVF8-LrFMmpwA0T2VW8',
    appId: '1:696407976562:android:8081bf86a0ffba6618f0eb',
    messagingSenderId: '696407976562',
    projectId: 'test-work-app-4bb89',
    storageBucket: 'test-work-app-4bb89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAyx1Dv4ZzZhJmMxSp6i6mJJXABMxPLXo',
    appId: '1:696407976562:ios:d12de78bab7a728318f0eb',
    messagingSenderId: '696407976562',
    projectId: 'test-work-app-4bb89',
    storageBucket: 'test-work-app-4bb89.firebasestorage.app',
    iosBundleId: 'com.example.testWorkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAyx1Dv4ZzZhJmMxSp6i6mJJXABMxPLXo',
    appId: '1:696407976562:ios:d12de78bab7a728318f0eb',
    messagingSenderId: '696407976562',
    projectId: 'test-work-app-4bb89',
    storageBucket: 'test-work-app-4bb89.firebasestorage.app',
    iosBundleId: 'com.example.testWorkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHMWEZlKtJp7FHcyuxv7fA1rP9vWAIZO4',
    appId: '1:696407976562:web:c3414ea0cce1ebc618f0eb',
    messagingSenderId: '696407976562',
    projectId: 'test-work-app-4bb89',
    authDomain: 'test-work-app-4bb89.firebaseapp.com',
    storageBucket: 'test-work-app-4bb89.firebasestorage.app',
  );
}
